-- Final — Build 93 unified green certificates (zero axiom, zero sorry)
--
-- ClayFinalClean        : 10-way native_decide conjunction, all numerical values
--                         reproducible, forbidden? False, len=3636
-- ClayFinalUnifiedClean : same unified across all seven modules
--
-- Note: build each file individually — they share top-level definitions
--   lake build Final.ClayFinalClean
--   lake build Final.ClayFinalUnifiedClean
