-- MMW — Magnification (MMW 2019): small lower bound → NP ⊄ P/poly → P≠NP
--
-- ClayMMWClean         : L_GapMCSP=64 > 33=N^{1.01}, 9765625 < 10892522,
--                        anti-checker 50≤50, GapMCSP_in_NP_green, Build 93 CLEAN
-- ClayMagnification    : magnification hypothesis formal statement
-- ClayRealMagnification: real-valued magnification bounds
-- ClayRealMCSP         : GapMCSP ∈ NP, anti-checker concrete
--
-- Note: build each file individually — they share top-level definitions
--   lake build MMW.ClayMMWClean
